#!/bin/bash

# Mettre à jour le systême

sudo apt update

sudo apt full-upgrade -y

# Installer les logiciels de base

sudo apt install preload openssh-server filezilla wget python3 software-properties-common firefox thunderbird zsh ufw curl git rsync 

# Configuration ssh

cp ~/InstallScripts/ssh_config /etc/ssh/ssh_config

cp ~/InstallScripts/sshd_config /etc/ssh/sshd_config

sudo service sshd reload


# Configuration du pare-feu

sudo ufw enable

sudo ufw allow 1990,2049,80,443/tcp

sudo ufw deny 22

sudo ufw reload


# Installer zsh et OhMyZsh!

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/to$

cp ~/InstallScripts/.zshrc ~/.zshrc



#Installer le client nextcloud

wget https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.6.1-x86_64.AppImage

chmod a+x ./Nextcloud-2.6.1-x86_64.AppImage

./Nextcloud-2.6.1-x86_64.AppImage
