#!/bin/bash


# Script d'installation du sudolkserver comprenant le nextcloud, les 
# différents sites web installés et les config réseaux diverses

#&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%&&%&&%%%%%%%%%%%%&&&&&&&&&&&%%%%%%%%%%%%%%%%%%%%%%%%&&&&
#&&&&&&&@@&&&&&&&&&&&&&&&&&&&&&&@&&&&&&&%&&&&&&&&&%%%%&&&&%%%%%&&&&&&&&&&%%%%%%%%%%%%%%%%%%%%%%%&%&&
#&&&&&@@@&&@@&&&&&&&&&&&&&&&&&&&@&&&&%%%%&&&&&&%%%%%%%%&@@@@@@@@@@@&&&&&%%&%%%%%%%%%%%%%%%%%%%%&%&&&
#&&&&&@@&&&&&&&&&@&&&&@&&&&&&&&&@&&&%%%%%&&&&&&&&&&&&@@@@@@@@@@@@@@@@@@&&&%&%%%%%%%%%%%%%%%%%%%%%&&&
#&%&&@@&&&&&&&&&&@&&&&@&&&&%&&&&@%&@@@@@@&@&&&&&&&&@@@@@@@@@@@@@@@@@@@@@@@&&&&%%%%&%%%%%%%%%%%%%&&&&
#%&&&&@@@@&&&&&&&@&&&&@&&&@@@@@@%@@%%%%%%@@&&&&&&@@@@@&%%%%%%&&&@@@@@@@@@@@&%&&%%%%%%%%%%%%%%%&&&&&
#%%%&%%&@@@&&&&&&@&&&&@&&&@@%%%%@@@%%%%%%@@%&&&&@@@@&%%###########%%&&@@@@@@@&&&&&&%%%%%%%%%%%&&&&&&
#%%%%%%%%&&@@&&%&@&&&&@&&&@@&%%@%%@%%%%%@@@&&&&&@@@&%####(((((((####%%&@@@@@@@&%%&&&%%%%%%%%&&&&&&&&
#&%%%%%@@@@@&&&&&@&&&@%%&%%&@%@%%%%@@@@@@@&&&&&&@@%%%###((((((((#####%%%&@@@@@@%%%%&%&%%%%%%&&&&&&&&
#%%%%%%%%%%%%%&&%@@@@%%&%%%%%%%%%%%%%%%%%&&&&&&&&%%##(((((((((((######%%&@@@@@@%%%%%%%&&&%%&&&&&&&&&
#%%%%%%&%%%%%%%&%%%%%%%%%%&%%%%%%%%%%%%%%&&&&&%#&&%&&&%((//////((((####%%@@@@@@%%&%&%%&%%%%%&%%&&&&&
#%%%%%%%%%%%%&&&%%%%%%%&%%%%%%%%%%%%%%%%%&&&&&%%&%%%%%&&%###((####(%%%%%%%&@@@@%%%%%%%%%%%%%%&&&&&&&
#&&&&&&&%%%%%%%%&%&&&%%%%&%%%%%%%%%%%%%%&&&&%&%%##%&%%##,//(/#%%%%%%&&&&%%#@@@@%%%%%%%%%%%%%%%%&&&&&
#%%%&&%%%%%%%%%%%&%%%%%%%%%%%%%%%%%%%%%%&&&&%####%%###(#((##### /#%%%&%%&&@@%%%%%%%%%%%%%%%%&&%&&&
#%%%@@%%%%%%%%@%%%@%%%%@@@@@@@@%%%%%%%%%&%%%#&%#(#########(((/#(((##%%%%%&@&&&%%%%%%%%%%%%%%%%%&&&&&
#%%%@@%%%%%%%%@%@@@%%%%@&%%%%%@&%%%%%%%%&&%%%&%#(((((((##(((####((####%%%%%%%%%%%%%%%%%%%%%%%%%&%&&&
#%%%@@%%%%%%%%@@&%%%%%%@&%%&@@@%%%%%%%%%&&%%%&%#(((////#(///(#(((###%%#%%&%%%%%%%%%%%%%%%%%%%%%%%%%&
#%%%@%%%%%%%%%@@%%%%%%%@@@@%%%%%%%%%%%%%%%&%%&%#(((//*/(#(/###//((((###%&#%%%%%%%%%%%%%%%%%%%%%%%&
#%%%@%%%%%%%%%@%@@%%%%%@@%%@@%%%%%%%%%%%%%%%%%%#((///((((((((////(((##%%&&%%%%%%%%%%%%%%%%%%%%%&%%%&
#%%%@@@@@@@%%%@%%@@%%%%@@%%%%@%%%%%%%%%%%%%%%%%#(((###%%##%#((((/((###%%&%%&&@&%%%%%%%%%%%%%%%%%%%&&
#%%%%%%%%%%%%%%%%%%%%%%&@%%%%%%%%%%%%%%%%%%%%%%%##((#%%%%##((##%(((##%%&@@@&&&&%%%%%%%%%%%%%%%%%&&&&
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##(#((((/(((((((###%%&%%&&&%%%%%%%%%%%%%%%%%%%%%%%&
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#(((//((((((((##%%%&%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#&&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#(((((((((((#%%%%&%%%%%%%%%%%%%%%%%%%%&&&&@&&@&&&
#&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%&#((((((((#%%%%%%%%%%%%%%%%%%%%%%%%%&&&&&&&&&&@@@
#&&&&&%%%%%%%%%%%mange%tes%morts%%%%%%%%%%%%%%%%%&&@&&%&%%%%%&&%%%%%&&%%%%%%%%%%%&%&&&&&&&&&&&@&@@@@
#&&&&%&%%%%%%%%%%%%%%&%%%%%%%%%%%%%%%%%%%%%%%%%%%&%%&@@&&&&&&&%%#%%%%&&&&&%&&&&&%%&&&&&&&&&&&@@@@@@@
#&&&&&%&&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%&%#%%%%########%%%%&&&&%%%%&&&%%&&&&&&&&&&&&&&@&@@@



sudo apt update

sudo apt full-upgrade -y


# 1 Monter les disques et copier les scripts

mkdir ~/GROSNB

sudo mount -t ext4 /dev/sdb1 /home/sudolkr/GROSNB

sudo cp /home/sudolkr/GROSNB/SMPLCF/SMPLCF/fstab1 /etc/fstab

sudo mount -a

# A FINIR: copie des scripts

#sudo cp /home/sudolkr/GROSNB/SMPLCF/bin/


# 2 Assignations DHCP 

sudo cp /home/sudolkr/GIANTNB/GROSNB/SMPLCF/SMPLCF/hosts /etc/hosts


# 3 Installer les logiciels de base 

sudo apt install nfs-kernel-server software-properties-common curl git rsync zsh ufw python3 vsftpd -y 


# 4 Mettre en place l'export des disques durs sur le réseau local

sudo service nfs-kernel-server start

sudo cp /home/sudolkr/GROSNB/SMPLCNF/SMPLCNF/exports /etc/exports

sudo service nfs-kernel-server restart


# 5 Configuration ssh

cp /home/sudolkr/GROSNB/SMPLCNF/SMPLCNF/ssh_config /etc/ssh/ssh_config

cp /home/sudolkr/GROSNB/SMPLCNF/SMPLCNF/sshd_config /etc/ssh/sshd_config

sudo service sshd reload


# 6 Configuration du pare-feu

sudo ufw enable

sudo ufw allow 1990,2049,80,443,3306,9000/tcp

sudo ufw deny 22

sudo ufw reload


# 7 Installer zsh et OhMyZsh!

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

cp /home/sudolkr/GROSNB/SMPLCNF/SMPLCNF/.zshrc /home/sudolkr/.zshrc


# 8 Installation de docker,nextcloud,mariadb et letsencrypt
 
sudo snap install docker

sudo systmctl start docker

sudo systmctl enable docker

sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

git clone https://github.com/ichiTechs/Dockerized-SSL-NextCloud-with-MariaDB.git

cd Dockerized-SSL-NextCloud-with-MariaDB

cp /home/sudolkr/GROSNB/SMPLCF/SMPLCF/docker-compose.yml /home/sudolkr/Doclerizd-SSL-NextCloud-wiyh-MariaDB/docker-compose.yml

sudo docker network create nginx-proxy

sudo docker-compose up -d db

sudo docker-compose up -d 






